### ISSUE TITLE
Iteration Plan for June 2021

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-webview-ui-toolkit#113]
This plan captures our work in **June**. We will ship our preview release **July 01 2021**.

Our goal for this iteration is to enable internal extension authors to consume the toolkit so we can gather feedback and ideas. We're tracking the following outcomes for this iteration:

- P0 components are available via public NPM package
- Devs can reference usage guides, sample extensions, and Storybook examples
- Component theming is fully configured

[Storybook](https://microsoft.github.io/vscode-webview-toolkit/)

## Plan Items
Below is a summary of the top-level plan items.

## Components

- [x] Badge
  - [x] Split into Badge and Tag components (#117)
- [x] Breadcrumb (incl. Breadcrumb Item)
- [x] Button
- [x] Checkbox
- [x] Combobox
- [x] Data Grid
  - [ ] Fix `rowsData` method bug (#120)
- [x] Divider
- [x] Dropdown
  - [x] Convert dropdown styling to align to VS Code (#142)
- [x] Link
- [x] Number Field
- [x] Panels
- [x] Progress Bar
- [x] Progress Ring
- [x] Radio Group (incl. Radio)
- [x] Tag
- [x] Text Area
- [x] Text Field

## Theming, Styles, and Layout

- [x] Create design token for remaining component magic values (#121)
- [x] Unify input border styles (#95)
- [x] Simplify design unit implementation (#115)

## Accessibility

- [ ] Check that all accessibility Storybook tests are passing
- [ ] Check that [VS Code accessibility standards](https://code.visualstudio.com/docs/editor/accessibility) are being met
- [ ] Run [Accessibility Insights](https://accessibilityinsights.io/) on toolkit

## Infrastructure

- [x] Add Microsoft copyright boilerplate to the top of each source code file

## Testing

- [ ] Write unit tests for utility scripts

## Docs

- [x] Prevent Storybook from triggering window shortcuts while typing in input components (#96)
- [x] Add value attribute documentation to relevant components
- [x] Validate documentation for readability and correctness

## Sample Extensions

- [x] [Hello World](https://github.com/microsoft/vscode-webview-toolkit-samples/tree/main/hello-world) 
- [x] [Weather](https://github.com/microsoft/vscode-webview-toolkit-samples/tree/main/weather-webview)
- [x] Update samples to use latest version of toolkit
